##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.19.2] date: [Wed Sep 04 16:24:34 CST 2024] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = CollectBoard_v1


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
X-CUBE-AI/App/bilstm_model.c \
X-CUBE-AI/App/bilstm_model_data.c \
X-CUBE-AI/App/bilstm_model_data_params.c \
X-CUBE-AI/App/aiSystemPerformance.c \
X-CUBE-AI/App/aiTestHelper.c \
X-CUBE-AI/App/syscalls.c \
X-CUBE-AI/App/aiTestUtility.c \
X-CUBE-AI/App/ai_device_adaptor.c \
X-CUBE-AI/App/lc_print.c \
X-CUBE-AI/App/app_x-cube-ai.c \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/crc.c \
Core/Src/fmc.c \
Core/Src/spi.c \
Core/Src/tim.c \
Core/Src/usart.c \
Core/Src/ad7606.c \
Core/Src/font.c \
Core/Src/key_manager.c \
Core/Src/key.c \
Core/Src/lcd.c \
Core/Src/multi_button.c \
Core/Src/tasks_main.c \
Core/Src/stm32h7xx_it.c \
Core/Src/stm32h7xx_hal_msp.c \
LVGL/generated/events_init.c \
LVGL/generated/gui_guider.c \
LVGL/generated/widgets_init.c \
LVGL/generated/setup_scr_screen.c \
LVGL/generated/setup_scr_screen_1.c \
LVGL/generated/setup_scr_screen_2.c \
LVGL/generated/guider_fonts/lv_font_montserratMedium_12.c \
LVGL/generated/guider_fonts/lv_font_montserratMedium_14.c \
LVGL/generated/guider_fonts/lv_font_montserratMedium_15.c \
LVGL/generated/guider_fonts/lv_font_montserratMedium_16.c \
LVGL/generated/guider_fonts/lv_font_montserratMedium_18.c \
LVGL/generated/guider_fonts/lv_font_montserratMedium_20.c \
LVGL/generated/guider_fonts/lv_font_SourceHanSerifSC_Regular_18.c \
LVGL/generated/images/_R_alpha_136x117.c \
LVGL/generated/images/_F5_20x20.c \
LVGL/generated/images/_F5_alpha_20x20.c \
LVGL/generated/images/_back_20x20.c \
LVGL/generated/images/_back_240x320.c \
LVGL/generated/images/_off_20x20.c \
LVGL/generated/images/_off_240x320.c \
LVGL/custom/custom.c \
LVGL/lvgl/porting/lv_port_disp.c \
LVGL/lvgl/porting/lv_port_fs.c \
LVGL/lvgl/porting/lv_port_indev.c \
LVGL/lvgl/src/core/lv_disp.c \
LVGL/lvgl/src/core/lv_event.c \
LVGL/lvgl/src/core/lv_group.c \
LVGL/lvgl/src/core/lv_indev_scroll.c \
LVGL/lvgl/src/core/lv_indev.c \
LVGL/lvgl/src/core/lv_obj_class.c \
LVGL/lvgl/src/core/lv_obj.c \
LVGL/lvgl/src/core/lv_obj_draw.c \
LVGL/lvgl/src/core/lv_obj_pos.c \
LVGL/lvgl/src/core/lv_obj_scroll.c \
LVGL/lvgl/src/core/lv_obj_style.c \
LVGL/lvgl/src/core/lv_obj_style_gen.c \
LVGL/lvgl/src/core/lv_obj_tree.c \
LVGL/lvgl/src/core/lv_refr.c \
LVGL/lvgl/src/core/lv_theme.c \
LVGL/lvgl/src/draw/lv_draw.c \
LVGL/lvgl/src/draw/lv_draw_arc.c \
LVGL/lvgl/src/draw/lv_draw_img.c \
LVGL/lvgl/src/draw/lv_draw_label.c \
LVGL/lvgl/src/draw/lv_draw_layer.c \
LVGL/lvgl/src/draw/lv_draw_line.c \
LVGL/lvgl/src/draw/lv_draw_mask.c \
LVGL/lvgl/src/draw/lv_draw_rect.c \
LVGL/lvgl/src/draw/lv_draw_transform.c \
LVGL/lvgl/src/draw/lv_draw_triangle.c \
LVGL/lvgl/src/draw/lv_img_buf.c \
LVGL/lvgl/src/draw/lv_img_cache.c \
LVGL/lvgl/src/draw/lv_img_decoder.c \
LVGL/lvgl/src/draw/arm2d/lv_gpu_arm2d.c \
LVGL/lvgl/src/draw/nxp/pxp/lv_draw_pxp.c \
LVGL/lvgl/src/draw/nxp/pxp/lv_draw_pxp_blend.c \
LVGL/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp.c \
LVGL/lvgl/src/draw/nxp/pxp/lv_gpu_nxp_pxp_osa.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_arc.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_blend.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_line.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_draw_vglite_rect.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_vglite_buf.c \
LVGL/lvgl/src/draw/nxp/vglite/lv_vglite_utils.c \
LVGL/lvgl/src/draw/renesas/lv_gpu_d2_draw_label.c \
LVGL/lvgl/src/draw/renesas/lv_gpu_d2_ra6m3.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_arc.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_bg.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_composite.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_img.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_label.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_layer.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_line.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_mask.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_polygon.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_rect.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_stack_blur.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_texture_cache.c \
LVGL/lvgl/src/draw/sdl/lv_draw_sdl_utils.c \
LVGL/lvgl/src/draw/stm32_dma2d/lv_gpu_stm32_dma2d.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_arc.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_blend.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_dither.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_gradient.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_img.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_layer.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_letter.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_line.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_polygon.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_rect.c \
LVGL/lvgl/src/draw/sw/lv_draw_sw_transform.c \
LVGL/lvgl/src/draw/swm341_dma2d/lv_gpu_swm341_dma2d.c \
LVGL/lvgl/src/extra/lv_extra.c \
LVGL/lvgl/src/extra/layouts/flex/lv_flex.c \
LVGL/lvgl/src/extra/layouts/grid/lv_grid.c \
LVGL/lvgl/src/extra/libs/bmp/lv_bmp.c \
LVGL/lvgl/src/extra/libs/ffmpeg/lv_ffmpeg.c \
LVGL/lvgl/src/extra/libs/freetype/lv_freetype.c \
LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_fatfs.c \
LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_posix.c \
LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_stdio.c \
LVGL/lvgl/src/extra/libs/fsdrv/lv_fs_win32.c \
LVGL/lvgl/src/extra/libs/gif/gifdec.c \
LVGL/lvgl/src/extra/libs/gif/lv_gif.c \
LVGL/lvgl/src/extra/libs/png/lodepng.c \
LVGL/lvgl/src/extra/libs/png/lv_png.c \
LVGL/lvgl/src/extra/libs/qrcode/lv_qrcode.c \
LVGL/lvgl/src/extra/libs/qrcode/qrcodegen.c \
LVGL/lvgl/src/extra/libs/rlottie/lv_rlottie.c \
LVGL/lvgl/src/extra/libs/sjpg/lv_sjpg.c \
LVGL/lvgl/src/extra/libs/sjpg/tjpgd.c \
LVGL/lvgl/src/extra/others/fragment/lv_fragment.c \
LVGL/lvgl/src/extra/others/fragment/lv_fragment_manager.c \
LVGL/lvgl/src/extra/others/gridnav/lv_gridnav.c \
LVGL/lvgl/src/extra/others/ime/lv_ime_pinyin.c \
LVGL/lvgl/src/extra/others/imgfont/lv_imgfont.c \
LVGL/lvgl/src/extra/others/monkey/lv_monkey.c \
LVGL/lvgl/src/extra/others/msg/lv_msg.c \
LVGL/lvgl/src/extra/others/snapshot/lv_snapshot.c \
LVGL/lvgl/src/extra/themes/basic/lv_theme_basic.c \
LVGL/lvgl/src/extra/themes/default/lv_theme_default.c \
LVGL/lvgl/src/extra/themes/mono/lv_theme_mono.c \
LVGL/lvgl/src/extra/widgets/animimg/lv_animimg.c \
LVGL/lvgl/src/extra/widgets/calendar/lv_calendar.c \
LVGL/lvgl/src/extra/widgets/calendar/lv_calendar_header_arrow.c \
LVGL/lvgl/src/extra/widgets/calendar/lv_calendar_header_dropdown.c \
LVGL/lvgl/src/extra/widgets/chart/lv_chart.c \
LVGL/lvgl/src/extra/widgets/colorwheel/lv_colorwheel.c \
LVGL/lvgl/src/extra/widgets/imgbtn/lv_imgbtn.c \
LVGL/lvgl/src/extra/widgets/keyboard/lv_keyboard.c \
LVGL/lvgl/src/extra/widgets/led/lv_led.c \
LVGL/lvgl/src/extra/widgets/list/lv_list.c \
LVGL/lvgl/src/extra/widgets/menu/lv_menu.c \
LVGL/lvgl/src/extra/widgets/meter/lv_meter.c \
LVGL/lvgl/src/extra/widgets/msgbox/lv_msgbox.c \
LVGL/lvgl/src/extra/widgets/span/lv_span.c \
LVGL/lvgl/src/extra/widgets/spinbox/lv_spinbox.c \
LVGL/lvgl/src/extra/widgets/spinner/lv_spinner.c \
LVGL/lvgl/src/extra/widgets/tabview/lv_tabview.c \
LVGL/lvgl/src/extra/widgets/tileview/lv_tileview.c \
LVGL/lvgl/src/extra/widgets/win/lv_win.c \
LVGL/lvgl/src/font/lv_font.c \
LVGL/lvgl/src/font/lv_font_dejavu_16_persian_hebrew.c \
LVGL/lvgl/src/font/lv_font_fmt_txt.c \
LVGL/lvgl/src/font/lv_font_loader.c \
LVGL/lvgl/src/font/lv_font_montserrat_10.c \
LVGL/lvgl/src/font/lv_font_montserrat_12.c \
LVGL/lvgl/src/font/lv_font_montserrat_12_subpx.c \
LVGL/lvgl/src/font/lv_font_montserrat_14.c \
LVGL/lvgl/src/font/lv_font_montserrat_16.c \
LVGL/lvgl/src/font/lv_font_montserrat_18.c \
LVGL/lvgl/src/font/lv_font_montserrat_20.c \
LVGL/lvgl/src/font/lv_font_montserrat_22.c \
LVGL/lvgl/src/font/lv_font_montserrat_24.c \
LVGL/lvgl/src/font/lv_font_montserrat_26.c \
LVGL/lvgl/src/font/lv_font_montserrat_28.c \
LVGL/lvgl/src/font/lv_font_montserrat_28_compressed.c \
LVGL/lvgl/src/font/lv_font_montserrat_30.c \
LVGL/lvgl/src/font/lv_font_montserrat_32.c \
LVGL/lvgl/src/font/lv_font_montserrat_34.c \
LVGL/lvgl/src/font/lv_font_montserrat_36.c \
LVGL/lvgl/src/font/lv_font_montserrat_38.c \
LVGL/lvgl/src/font/lv_font_montserrat_40.c \
LVGL/lvgl/src/font/lv_font_montserrat_42.c \
LVGL/lvgl/src/font/lv_font_montserrat_44.c \
LVGL/lvgl/src/font/lv_font_montserrat_46.c \
LVGL/lvgl/src/font/lv_font_montserrat_48.c \
LVGL/lvgl/src/font/lv_font_montserrat_8.c \
LVGL/lvgl/src/font/lv_font_simsun_16_cjk.c \
LVGL/lvgl/src/font/lv_font_unscii_16.c \
LVGL/lvgl/src/font/lv_font_unscii_8.c \
LVGL/lvgl/src/hal/lv_hal_disp.c \
LVGL/lvgl/src/hal/lv_hal_indev.c \
LVGL/lvgl/src/hal/lv_hal_tick.c \
LVGL/lvgl/src/misc/lv_anim.c \
LVGL/lvgl/src/misc/lv_anim_timeline.c \
LVGL/lvgl/src/misc/lv_area.c \
LVGL/lvgl/src/misc/lv_async.c \
LVGL/lvgl/src/misc/lv_bidi.c \
LVGL/lvgl/src/misc/lv_color.c \
LVGL/lvgl/src/misc/lv_fs.c \
LVGL/lvgl/src/misc/lv_gc.c \
LVGL/lvgl/src/misc/lv_ll.c \
LVGL/lvgl/src/misc/lv_log.c \
LVGL/lvgl/src/misc/lv_lru.c \
LVGL/lvgl/src/misc/lv_math.c \
LVGL/lvgl/src/misc/lv_mem.c \
LVGL/lvgl/src/misc/lv_printf.c \
LVGL/lvgl/src/misc/lv_style.c \
LVGL/lvgl/src/misc/lv_style_gen.c \
LVGL/lvgl/src/misc/lv_templ.c \
LVGL/lvgl/src/misc/lv_timer.c \
LVGL/lvgl/src/misc/lv_tlsf.c \
LVGL/lvgl/src/misc/lv_txt.c \
LVGL/lvgl/src/misc/lv_txt_ap.c \
LVGL/lvgl/src/misc/lv_utils.c \
LVGL/lvgl/src/widgets/lv_arc.c \
LVGL/lvgl/src/widgets/lv_bar.c \
LVGL/lvgl/src/widgets/lv_btn.c \
LVGL/lvgl/src/widgets/lv_btnmatrix.c \
LVGL/lvgl/src/widgets/lv_canvas.c \
LVGL/lvgl/src/widgets/lv_checkbox.c \
LVGL/lvgl/src/widgets/lv_dropdown.c \
LVGL/lvgl/src/widgets/lv_img.c \
LVGL/lvgl/src/widgets/lv_label.c \
LVGL/lvgl/src/widgets/lv_line.c \
LVGL/lvgl/src/widgets/lv_objx_templ.c \
LVGL/lvgl/src/widgets/lv_roller.c \
LVGL/lvgl/src/widgets/lv_slider.c \
LVGL/lvgl/src/widgets/lv_switch.c \
LVGL/lvgl/src/widgets/lv_table.c \
LVGL/lvgl/src/widgets/lv_textarea.c \
Core/Src/stm32h7xx_hal_timebase_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c \
Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c \
Core/Src/system_stm32h7xx.c

# ASM sources
ASM_SOURCES =  \
startup_stm32h743xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m7

# fpu
FPU = -mfpu=fpv5-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H743xx


# AS includes
AS_INCLUDES =  \
-ICore/Inc

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IX-CUBE-AI/App \
-IX-CUBE-AI \
-IX-CUBE-AI/Target \
-IMiddlewares/ST/AI/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc \
-IDrivers/STM32H7xx_HAL_Driver/Inc/Legacy \
-ILVGL/lvgl \
-ILVGL/lvgl/keypad_encoder \
-ILVGL/lvgl/porting \
-ILVGL/lvgl/src \
-ILVGL/lvgl/src/core \
-ILVGL/lvgl/src/draw \
-ILVGL/lvgl/src/draw/arm2d \
-ILVGL/lvgl/src/draw/nxp/pxp \
-ILVGL/lvgl/src/draw/nxp/vglite \
-ILVGL/lvgl/src/draw/renesas \
-ILVGL/lvgl/src/draw/sdl \
-ILVGL/lvgl/src/draw/stm32_dma2d \
-ILVGL/lvgl/src/draw/sw \
-ILVGL/lvgl/src/draw/swm341_dma2d \
-ILVGL/lvgl/src/extra \
-ILVGL/lvgl/src/extra/layouts \
-ILVGL/lvgl/src/extra/layouts/flex \
-ILVGL/lvgl/src/extra/layouts/grid \
-ILVGL/lvgl/src/extra/libs \
-ILVGL/lvgl/src/extra/libs/bmp \
-ILVGL/lvgl/src/extra/libs/ffmpeg \
-ILVGL/lvgl/src/extra/libs/freetype \
-ILVGL/lvgl/src/extra/libs/fsdrv \
-ILVGL/lvgl/src/extra/libs/gif \
-ILVGL/lvgl/src/extra/libs/png \
-ILVGL/lvgl/src/extra/libs/qrcode \
-ILVGL/lvgl/src/extra/libs/rlottie \
-ILVGL/lvgl/src/extra/libs/sjpg \
-ILVGL/lvgl/src/extra/others \
-ILVGL/lvgl/src/extra/others/fragment \
-ILVGL/lvgl/src/extra/others/gridnav \
-ILVGL/lvgl/src/extra/others/ime \
-ILVGL/lvgl/src/extra/others/imgfont \
-ILVGL/lvgl/src/extra/others/monkey \
-ILVGL/lvgl/src/extra/others/msg \
-ILVGL/lvgl/src/extra/others/snapshot \
-ILVGL/lvgl/src/extra/themes \
-ILVGL/lvgl/src/extra/themes/basic \
-ILVGL/lvgl/src/extra/themes/default \
-ILVGL/lvgl/src/extra/themes/mono \
-ILVGL/lvgl/src/extra/widgets \
-ILVGL/lvgl/src/extra/widgets/animimg \
-ILVGL/lvgl/src/extra/widgets/calendar \
-ILVGL/lvgl/src/extra/widgets/chart \
-ILVGL/lvgl/src/extra/widgets/colorwheel \
-ILVGL/lvgl/src/extra/widgets/imgbtn \
-ILVGL/lvgl/src/extra/widgets/keyboard \
-ILVGL/lvgl/src/extra/widgets/led \
-ILVGL/lvgl/src/extra/widgets/list \
-ILVGL/lvgl/src/extra/widgets/menu \
-ILVGL/lvgl/src/extra/widgets/meter \
-ILVGL/lvgl/src/extra/widgets/msgbox \
-ILVGL/lvgl/src/extra/widgets/span \
-ILVGL/lvgl/src/extra/widgets/spinbox \
-ILVGL/lvgl/src/extra/widgets/spinner \
-ILVGL/lvgl/src/extra/widgets/tabview \
-ILVGL/lvgl/src/extra/widgets/tileview \
-ILVGL/lvgl/src/extra/widgets/win \
-ILVGL/lvgl/src/font \
-ILVGL/lvgl/src/hal\ \
-ILVGL/lvgl/src/misc \
-ILVGL/lvgl/src/widgets \
-ILVGL/generated \
-ILVGL/generated/guider_customer_fonts \
-ILVGL/custom \
-IDrivers/CMSIS/Device/ST/STM32H7xx/Include \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H743VITx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys  \
-l:NetworkRuntime810_CM7_GCC.a
LIBDIR =  \
-LMiddlewares/ST/AI/Lib
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) -Wl,--wrap=malloc -Wl,--wrap=free  -u _printf_float -Wl,--start-group $(LIBS) -Wl,--end-group -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
